global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Custom MySQL metrics exporter
  - job_name: 'mysql-metrics'
    static_configs:
      - targets: ['metrics_exporter:8000']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
